# Generated by Django 4.2.10 on 2025-06-21 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rut", models.CharField(max_length=12, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Administrador", "Administrador"),
                            ("Cliente", "Cliente"),
                        ],
                        default="Cliente",
                        max_length=15,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("username", models.CharField(max_length=150, unique=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProyectoInmobiliario",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                ("ubicacion", models.CharField(max_length=255)),
                ("fecha_inicio", models.DateField()),
                ("fecha_finalizacion", models.DateField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("En construcción", "En construcción"),
                            ("Terminado", "Terminado"),
                            ("Planificación", "Planificación"),
                            ("Cancelado", "Cancelado"),
                        ],
                        default="Planificación",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("codigo", models.CharField(max_length=20, unique=True)),
            ],
            options={
                "verbose_name": "Proyecto Inmobiliario",
                "verbose_name_plural": "Proyectos Inmobiliarios",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UnidadPropiedad",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("numero_unidad", models.CharField(max_length=20)),
                (
                    "tipo_unidad",
                    models.CharField(
                        choices=[
                            ("Departamento", "Departamento"),
                            ("Casa", "Casa"),
                            ("Oficina", "Oficina"),
                            ("Local", "Local Comercial"),
                            ("Terreno", "Terreno"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "metraje_cuadrado",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("precio_venta", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Disponible", "Disponible"),
                            ("Vendido", "Vendido"),
                            ("Reservado", "Reservado"),
                        ],
                        default="Disponible",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="propiedades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unidades",
                        to="real_estate.proyectoinmobiliario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unidad de Propiedad",
                "verbose_name_plural": "Unidades de Propiedad",
                "ordering": ["numero_unidad"],
                "unique_together": {("proyecto", "numero_unidad")},
            },
        ),
    ]
